s3:
  drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/sunp/lm_ar
  outflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/sunp/lm_ar
  targets:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/targets/bvre
  forecasts:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  restart:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
   site_id: bvre
   name: Beaverdam Reservoir
   latitude: 37.307   #Degrees North
   longitude: 79.81607  #Degrees West
da_setup:
    use_obs_constraint: TRUE
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size: 256
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    obs_filename: bvre-targets-insitu.csv
    localization_distance: .na
model_settings:
   ncore: 4
   model_name: glm #other is "null"
   base_GLM_nml: glm3.nml
   max_model_layers: 100
   # modeled_depths: [0.00, 0.25, 0.50, 0.75,
   #                  1.00, 1.25, 1.50, 1.75,
   #                  2.00, 2.25, 2.50, 2.75,
   #                  3.00, 3.25, 3.50, 3.75,
   #                  4.00, 4.25, 4.50, 4.75,
   #                  5.00, 5.25, 5.50, 5.75,
   #                  6.00, 6.50, 7.00, 7.50,
   #                  8.00, 8.50, 9.00, 9.50,
   #                  10.00, 10.50, 11.00, 11.50,
   #                  12.00, 12.50, 12.00, 12.50,
   #                  13.00] 
   modeled_depths: [0.00, 0.50, 1.00, 1.50,
                    2.00, 2.50, 3.00, 3.50,
                    4.00, 4.50, 5.00, 5.50,
                    6.00, 6.50, 7.00, 7.50,
                    8.00, 8.50, 9.00, 9.50,
                    10.00, 11.00, 12.00, 13.00]
   par_config_file: parameter_calibration_config.csv #change this to NULL to keep parmeters constant
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 13  #not a modeled state
   temp: [4.8,4.8,4.78,4.76,4.73,4.73,4.73,4.73,4.71,4.71,4.7,4.7,4.7,4.7] #27,26,23,23,14,11,10,9,9,9,9,9
   temp_depths: [0.1,1,2,3,4,5,6,7,8,9,10,11,12,13] 
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
flows:
   include_inflow: FALSE
   include_outflow: FALSE
   forecast_inflow_model: inflow-xbgoost
   #observed_inflow_filename: NA
   #inflow_variables: NA
   historical_inflow_model: historic/model_id=inflow-xbgoost
   future_inflow_model: future/model_id=inflow-xbgoost
   historical_outflow_model: historic/model_id=inflow-xbgoost
   future_outflow_model: future/model_id=inflow-xbgoost
   local_inflow_directory: drivers/inflow
   local_outflow_directory: drivers/outflow
   use_flows_s3: no
   use_ler_vars: no
   #use_forecasted_inflow: TRUE
met:
   future_met_model: 'gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}'
   historical_met_model: 'gefs-v12/stage3/site_id={site_id}'
   historical_met_use_s3: TRUE
   future_met_use_s3: TRUE
   use_openmeteo: FALSE
   local_met_directory: 'drivers'
   use_forecasted_met: TRUE
   use_ler_vars: FALSE
   forecast_lag_days: 1
uncertainty:
   #observation_uncertainty: TRUE
   #process_uncertainty: TRUE
   #weather_uncertainty: TRUE
   #initial_condition_uncertainty: TRUE
   #parameter_uncertainty: TRUE
   #met_downscale_uncertainty: TRUE
   #inflow_process_uncertainty: TRUE
   
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter]
   generate_plots: FALSE
   # diagnostics_daily:
   #    names: ['Tot Inflow Vol', 'Tot Outflow Vol', 'Overflow Vol', 'temp']
   #    save_names: ['inflow', 'outflow','overflow', 'temp_outflow']
   #    file: ['lake.csv', 'lake.csv','lake.csv', 'outlet_00.csv']
   #    depth: [NA, NA, NA, NA]
